services:
  kv_0:
    build:
      context: .
    environment:
      RAFT_LEADER: ""
      RAFT_ADDRESS: "kv_0"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - kv_network

  kv_2:
    build:
      context: .
    environment:
      RAFT_LEADER: "http://kv_0:8080"
      RAFT_ADDRESS: "kv_2"
    ports:
      - "8082:8080"
      - "8083:8081"
    networks:
      - kv_network

  kv_4:
    build:
      context: .
    environment:
      RAFT_LEADER: "http://kv_0:8080"
      RAFT_ADDRESS: "kv_4"
    ports:
      - "8084:8080"
      - "8085:8081"
    networks:
      - kv_network

networks:
  kv_network:
    driver: bridge
